### ISSUE TITLE
连接不上mysql8.0.36

### ISSUE THREAD

**Issue by LanQianzi** [drogonframework/drogon-docs#68]
我使用的是fedora39软件包 mysql-community-devel-8.0.36-10.fc39.x86_64 已安装。但是使用find_package(MySQL REQUIRED)报错Cannot find MySQL.所在位置为/usr/local/lib64/cmake/Drogon/FindMySQL.cmake:120然后我去这个文件里面更改在find_library(MYSQL_LIBRARIES)的PATHS添加了/usr/lib64/mysql然后在NAMES 添加了mysqlclient才编译过了但是运行的时候还是报错:20240418 13:03:59.663759 UTC 9575 FATAL No database is supported by drogon, please install the database development library first. - DbClientManagerSkipped.cc:44
[1]    9575 IOT instruction (core dumped)

这是为什么是因为这个库不支持mysql-community-devel-8.0.36-10.fc39.x86_64 吗？

**Comment by an-tao** [comment]
客户端库要用mariadb的，请参考wiki里的介绍。

**Comment by LanQianzi** [comment]
但是我输入sudo dnf install mariadb-devel他自动给我下载了mysql-community-devel-8.0.36-10.fc39.x86_64了

**Comment by an-tao** [comment]
请问是哪个发行版，环境详述一下，我看看能不能复现

**Comment by LanQianzi** [comment]
fedora 39
neko$ sudo dnf install mariadb-devel                        
[sudo] neko 的密码：
上次元数据过期检查：2:23:57 前，执行于 2024年04月19日 星期五 15时24分27秒。
软件包 mysql-community-devel-8.0.36-10.fc39.x86_64 已安装。
依赖关系解决。
无需任何处理。
完毕！

**Comment by LanQianzi** [comment]
不过为这个是已经根据mysql官方文档安装过mysql server版本了，是不是得现卸载？

**Comment by an-tao** [comment]
> 不过为这个是已经根据mysql官方文档安装过mysql server版本了，是不是得现卸载？

不需要，server端mysql和mariadb是兼容的，drogon只要求client driver库是mariadb的。不过你最好确定没有安装mysql的客户端库，以免冲突。

**Comment by an-tao** [comment]
你的环境我得装一个虚拟机试试

**Comment by LanQianzi** [comment]
谢谢，麻烦你啦

**Comment by LanQianzi** [comment]
那个解决了我直接去的mariadb的github仓库克隆用源码安装了，谢谢你啦
